# node version specified via .nvmrc
language: node_js

# perform build tasks
script:
  - npm run lint
  - npm test
  - npm run build

# speed up builds by caching node modules
cache:
  directories:
    - node_modules

# turn off email notifications
notifications:
  email: false
